const menuItems = [
  {
    title: "Vegan Burger",
    description: "A plant-based burger with fresh toppings.",
    price: 10.99,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_vegan_burger_image",
  },
  {
    title: "Cheeseburger",
    description: "Classic cheeseburger with all the fixings.",
    price: 12.99,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_cheeseburger_image",
  },
  {
    title: "Vegan Pizza",
    description: "Delicious pizza topped with vegan cheese.",
    price: 11.49,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_vegan_pizza_image",
  },
  {
    title: "Pepperoni Pizza",
    description: "A classic pepperoni-topped pizza.",
    price: 13.49,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_pepperoni_pizza_image",
  },
  {
    title: "Tofu Stir Fry",
    description: "Stir-fried tofu with mixed vegetables.",
    price: 9.99,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_tofu_stir_fry_image",
  },
  {
    title: "Chicken Stir Fry",
    description: "Chicken stir-fry with fresh vegetables.",
    price: 12.49,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_chicken_stir_fry_image",
  },
  {
    title: "Quinoa Salad",
    description: "Healthy quinoa salad with fresh greens.",
    price: 8.99,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_quinoa_salad_image",
  },
  {
    title: "Caesar Salad",
    description: "Caesar salad with creamy dressing.",
    price: 10.99,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_caesar_salad_image",
  },
  {
    title: "Chickpea Curry",
    description: "Spicy chickpea curry with rice.",
    price: 9.49,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_chickpea_curry_image",
  },
  {
    title: "Beef Tacos",
    description: "Flavorful beef tacos with toppings.",
    price: 11.99,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_beef_tacos_image",
  },
  {
    title: "Lemonade",
    description: "Refreshing lemonade made fresh.",
    price: 3.5,
    vegan: true,
    food: false,
    drink: true,
    image: "url_to_lemonade_image",
  },
  {
    title: "Iced Coffee",
    description: "Chilled coffee with milk and ice.",
    price: 4.0,
    vegan: false,
    food: false,
    drink: true,
    image: "url_to_iced_coffee_image",
  },
  {
    title: "Coconut Water",
    description: "Hydrating coconut water.",
    price: 2.5,
    vegan: true,
    food: false,
    drink: true,
    image: "url_to_coconut_water_image",
  },
  {
    title: "Milkshake",
    description: "Creamy milkshake with rich flavors.",
    price: 5.0,
    vegan: false,
    food: false,
    drink: true,
    image: "url_to_milkshake_image",
  },
  {
    title: "Herbal Tea",
    description: "Soothing herbal tea blend.",
    price: 2.0,
    vegan: true,
    food: false,
    drink: true,
    image: "url_to_herbal_tea_image",
  },
  {
    title: "Soda",
    description: "Classic fizzy soda drink.",
    price: 1.5,
    vegan: true,
    food: false,
    drink: true,
    image: "url_to_soda_image",
  },
  {
    title: "Chocolate Cake",
    description: "Rich chocolate cake slice.",
    price: 4.5,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_chocolate_cake_image",
  },
  {
    title: "Fruit Salad",
    description: "Fresh mixed fruit salad.",
    price: 5.5,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_fruit_salad_image",
  },
  {
    title: "Pasta Primavera",
    description: "Pasta with fresh vegetables.",
    price: 10.99,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_pasta_primavera_image",
  },
  {
    title: "Grilled Cheese Sandwich",
    description: "Golden grilled cheese sandwich.",
    price: 8.5,
    vegan: false,
    food: true,
    drink: false,
    image: "url_to_grilled_cheese_image",
  },
  {
    title: "Vegetable Samosas",
    description: "Crispy vegetable-filled samosas.",
    price: 6.0,
    vegan: true,
    food: true,
    drink: false,
    image: "url_to_vegetable_samosas_image",
  },
];

export { menuItems };
