const menuItems = [
  {
    title: "Vegan Burger",
    price: "$10.99",
    type: "food",
    typev: "vegan",
    image: "https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-6-1024x1536.jpg",
  },
  {
    title: "Cheeseburger",
    price: "$12.99",
    type: "food",
    typev: "nonvegan",
    image: "https://theeburgerdude.com/wp-content/uploads/2024/03/McDons-Cheeseburgers-Feature-02B-1024x1024.jpg",
  },
  {
    title: "Vegan Pizza",
    price: "$11.49",
    type: "food",
    typev: "vegan",
    image: "https://simplegreensmoothies.com/wp-content/uploads/vegan-pizza-recipe-dough-vegetarian-dairy-free-30.jpg",
  },
  {
    title: "Pepperoni Pizza",
    price: "$13.49",
    type: "food",
    typev: "nonvegan",
    image: "https://cdn.shopify.com/s/files/1/0274/9503/9079/files/pepperoni-pizza_b3a5426b-38d7-4c34-9e3b-ef3217c144b6.jpg?v=1723644075?w=1024",
  },
  {
    title: "Tofu Stir Fry",
    price: "$9.99",
    type: "food",
    typev: "vegan",
    image: "https://simpleveganblog.com/wp-content/uploads/2023/01/easy-tofu-stir-fry.jpg",
  },
  {
    title: "Chicken Stir Fry",
    price: "$12.49",
    type: "food",
    typev: "nonvegan",
    image: "https://www.cookingclassy.com/wp-content/uploads/2019/12/chicken-stir-fry-1-600x900.jpg",
  },
  {
    title: "Quinoa Salad",
    price: "$8.99",
    type: "food",
    typev: "vegan",
    image: "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_728,h_546/k%2FPhoto%2FRecipes%2F2019-11-recipe-mediterranean-quinoa-salad%2F2019-10-21_Kitchn89095_Mediteranean-Quinoa-Salad",
  },
  {
    title: "Caesar Salad",
    price: "$10.99",
    type: "food",
    typev: "nonvegan",
    image: "https://s23209.pcdn.co/wp-content/uploads/2023/01/220905_DD_Chx-Caesar-Salad_051-760x1140.jpg",
  },
  {
    title: "Chickpea Curry",
    price: "$9.49",
    type: "food",
    typev: "vegan",
    image: "https://pinchofyum.com/cdn-cgi/image/width=680,height=99999,fit=scale-down/wp-content/uploads/Coconut-Curry-Chickpeas-62.jpg",
  },
  {
    title: "Beef Tacos",
    price: "$11.99",
    type: "food",
    typev: "nonvegan",
    image: "https://oliviaadriance.com/wp-content/uploads/2023/07/Final_3_Crispy_Baked_Beef_Tacos_grain-free-dairy-free.jpg.webp",
  },
  {
    title: "Lemonade",
    price: "$3.5",
    type: "drink",
    typev: "vegan",
    image: "https://greensmoothiegourmet.com/wp-content/uploads/2023/07/single-serving-lemonade3.jpg",
  },
  {
    title: "Iced Coffee",
    price: "$4.0",
    type: "drink",
    typev: "nonvegan",
    image: "https://www.forkinthekitchen.com/wp-content/uploads/2022/08/220629.iced_.latte_.vanilla-9009-600x600.jpg",
  },
  {
    title: "Coconut Water",
    price: "$2.5",
    type: "drink",
    typev: "vegan",
    image: "https://cdn.shopify.com/s/files/1/0948/1858/files/is_coconut_water_alkaline_1.jpg?v=1724999441",
  },
  {
    title: "Milkshake",
    price: "$5.0",
    type: "drink",
    typev: "nonvegan",
    image: "https://www.spoonforkbacon.com/wp-content/uploads/2023/05/make-milkshakes.jpg",
  },
  {
    title: "Herbal Tea",
    price: "$2.0",
    type: "drink",
    typev: "vegan",
    image: "https://tucsontea.com/cdn/shop/files/SP-sleep-herbal-tea-valerian-root-1000x1000.jpg?v=1705978659&width=1445",
  },
  {
    title: "Soda",
    price: "$1.5",
    type: "drink",
    typev: "vegan",
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRN6EP5-g6n06SUJktcsHQJ0ow6nea_I7Rw0k5WzdFKAKwwoNxwR4vQYB6qNj1IRymuofLwz6ORrBkhSNsb9r92h9C6mmm0hIYlCiXmyGEUskeYnaR1bmPx",
  },
  {
    title: "Chocolate Cake",
    price: "$4.5",
    type: "food",
    typev: "nonvegan",
    image: "https://scientificallysweet.com/wp-content/uploads/2023/06/IMG_4087-er-new1-720x910.jpg",
  },
  {
    title: "Fruit Salad",
    price: "$5.5",
    type: "food",
    typev: "vegan",
    image: "https://images.themodernproper.com/billowy-turkey/production/posts/2022/FruitSalad_Shot4_20.jpg?w=600&q=82&auto=format&fit=crop&dm=1654019861&s=4040d9c9eded22884a140e2887edd54c",
  },
  {
    title: "Pasta Primavera",
    price: "$10.99",
    type: "food",
    typev: "vegan",
    image: "https://images.themodernproper.com/billowy-turkey/production/posts/PastaPrimavera_10.jpg?w=600&q=82&auto=format&fit=crop&dm=1719193287&s=8010e05c677c223c23bd0f4ac48f188b",
  },
  {
    title: "Grilled Cheese Sandwich",
    price: "$8.5",
    type: "food",
    typev: "nonvegan",
    image: "https://www.onceuponachef.com/images/2024/01/Grilled-Cheese-6-760x1140.jpg",
  },
  {
    title: "Vegetable Samosas",
    price: "$6.0",
    type: "food",
    typev: "vegan",
    image: "https://www.yummytummyaarthi.com/wp-content/uploads/2022/09/veg-samosa-1.jpg",
  },
];

// Filter for vegan items
menuItems.filter((item) => item.typev === "vegan").forEach((i) => console.log(i));

export { menuItems };
