const menuItems = [
  {
    title: "Vegan Burger",
    price: 10.99,
    vegan: "vegan",
    type: "food",
    image: "url_to_vegan_burger_image",
  },
  {
    title: "Cheeseburger",
    price: 12.99,
    vegan: "nonvegan",
    type: "food",
    image: "url_to_cheeseburger_image",
  },
  {
    title: "Vegan Pizza",
    price: 11.49,
    vegan: "vegan",
    type: "food",
    image: "url_to_vegan_pizza_image",
  },
  {
    title: "Pepperoni Pizza",
    price: 13.49,
    vegan: "nonvegan",
    type: "food",
    image: "url_to_pepperoni_pizza_image",
  },
  {
    title: "Tofu Stir Fry",
    price: 9.99,
    vegan: "vegan",
    type: "food",
    image: "url_to_tofu_stir_fry_image",
  },
  {
    title: "Chicken Stir Fry",
    price: 12.49,
    vegan: "nonvegan",
    type: "food",
    image: "url_to_chicken_stir_fry_image",
  },
  {
    title: "Quinoa Salad",
    price: 8.99,
    vegan: "vegan",
    type: "food",
    image: "url_to_quinoa_salad_image",
  },
  {
    title: "Caesar Salad",
    price: 10.99,
    vegan: "nonvegan",
    type: "food",
    image: "url_to_caesar_salad_image",
  },
  {
    title: "Chickpea Curry",
    price: 9.49,
    vegan: "vegan",
    type: "food",
    image: "url_to_chickpea_curry_image",
  },
  {
    title: "Beef Tacos",
    price: 11.99,
    vegan: "nonvegan",
    type: "food",
    image: "url_to_beef_tacos_image",
  },
  {
    title: "Lemonade",
    price: 3.5,
    vegan: "vegan",
    type: "drink",
    image: "url_to_lemonade_image",
  },
  {
    title: "Iced Coffee",
    price: 4.0,
    vegan: "nonvegan",
    type: "drink",
    image: "url_to_iced_coffee_image",
  },
  {
    title: "Coconut Water",
    price: 2.5,
    vegan: "vegan",
    type: "drink",
    image: "url_to_coconut_water_image",
  },
  {
    title: "Milkshake",
    price: 5.0,
    vegan: "nonvegan",
    type: "drink",
    image: "url_to_milkshake_image",
  },
  {
    title: "Herbal Tea",
    price: 2.0,
    vegan: "vegan",
    type: "drink",
    image: "url_to_herbal_tea_image",
  },
  {
    title: "Soda",
    price: 1.5,
    vegan: "vegan",
    type: "drink",
    image: "url_to_soda_image",
  },
  {
    title: "Chocolate Cake",
    price: 4.5,
    vegan: "nonvegan",
    type: "dessert",
    image: "url_to_chocolate_cake_image",
  },
  {
    title: "Fruit Salad",
    price: 5.5,
    vegan: "vegan",
    type: "dessert",
    image: "url_to_fruit_salad_image",
  },
  {
    title: "Pasta Primavera",
    price: 10.99,
    vegan: "vegan",
    type: "food",
    image: "url_to_pasta_primavera_image",
  },
  {
    title: "Grilled Cheese Sandwich",
    price: 8.5,
    vegan: "nonvegan",
    type: "food",
    image: "url_to_grilled_cheese_image",
  },
  {
    title: "Vegetable Samosas",
    price: 6.0,
    vegan: "vegan",
    type: "food",
    image: "url_to_vegetable_samosas_image",
  },
];

export { menuItems };
